### ISSUE TITLE
Need better isolation for shortcuts

### ISSUE THREAD

**Issue by puzrin** [markdown-it/markdown-it-emoji#5]
Need netter algorythm to avoid conflicts between shortcuts and text

- [ ] `:/` conflicts with `http://`
- [ ] should we completely disable emojies in links?
- [ ] \w will not work with unicode

Ideas? Discuss.

**Comment by evaryont** [comment]
I think the simplest solution is to ensure that the emoji's are surrounded by whitespace. (Or if an emoji follows an emoji.)

**Comment by puzrin** [comment]
Resolved in master

**Comment by wizawu** [comment]
@puzrin 
I think the solution in dd6a247f58ec96e508edfe83bc9d620587cce3f5 is still buggy.

e.g. `:o` still conflicts with `:octocat:`.

:+1: for @evaryont 's solution.

**Comment by puzrin** [comment]
Thanks for info. I've created new ticket, sources of problems are different. `\w` does not support unicode, and will be movement to wrong direction.

If anyone has time, he an try to write regex generator, as `linkify-it does`.

**Comment by rlidwka** [comment]
> e.g. `:o` still conflicts with `:octocat:`.

I don't think it is. Here is the test I've come up with:

```js
var md = require('markdown-it')()
var emoji = require('markdown-it-emoji')

md.use(emoji, {
  defs: {
    'octocat': 'B',
    'ouch': 'A',
  },

  shortcuts: {
    ouch: [ ':o' ]
  }
})

console.log(md.render(':octocat:')
```

It'll produce `B`, and never `Actocat:`.

The reason is that when we build regexp, all emoticons [get sorted](https://github.com/markdown-it/markdown-it-emoji/blob/dd6a247f58ec96e508edfe83bc9d620587cce3f5/lib/normalize_opts.js#L46-L47), thus the resulting regexp would be `/:octocat:|:o/` and not the other way around.

As far as I know, regexp matching engine returns leftmost match, so it would always work:

```js
> /:octocat:|:o/.exec(':octocat:')
[ ':octocat:',
  index: 0,
  input: ':octocat:' ]
> /:o|:octocat:/.exec(':octocat:')
[ ':o',
  index: 0,
  input: ':octocat:' ]
```

Thus, no bug there.

**Comment by puzrin** [comment]
@wizawu did you tested your example or not prior to report?

**Comment by wizawu** [comment]
My case is rather simple.
```
var md = require('markdown-it')()
var emoji = require('markdown-it-emoji')

md.use(emoji)

console.log(md.render(':octocat:'))
```
The output is
```
<p>😮ctocat:</p>
```

The problem is not with the custom `:o` shortcut. It is with the default `:o` shortcut.

**Comment by wizawu** [comment]
I know where the problem is...
There is no `"octocat"` in `full.json`, so it would be just skipped.
